places = ['Paris', 'Miami', 'Los Angeles', 'Bei Jin', 'Hang Zhou']
print(places)
print("临时按开头字母顺序排序列表：\n" + str(sorted(places)))
print(places)
print()
print("临时按开头字母倒序排序列表：\n" + str(sorted(places, reverse=True)))
print(places)
print()
places.reverse()
print("反转列表顺序：\n" + str(places))
print()
places.reverse()
print("再次反转列表顺序：\n" + str(places))
print()
places.sort()
print("按首字母顺序排列列表：\n" + str(places))
print(places)